# Generated by Django 6.0.4 on 2026-05-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("statuses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="status",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creation date"),
        ),
    ]
